package gui;

import java.awt.CardLayout;

/*
Nama            : Deva Akbar Amin Amirullah
NPM             : 2010010802
Kelas           : 5A Non Reguler Banjarmasin
Prodi           : S-1 Teknik Informatika
Mata Kuliah     : Pemrograman Berbasis Objek 2 (PBO 2)
Dosen Pengampu  : Bapak Muhammad Edya Rosadi, M.Kom

Latihan 4
Menampilkan Gambar dengan Combo Box
*/

public class TampilGambarComboBox extends javax.swing.JFrame {

    /**
     * Creates new form TampilGambarComboBox
     */
    public TampilGambarComboBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboPanel = new javax.swing.JPanel();
        comboLB = new javax.swing.JLabel();
        pilihCB = new javax.swing.JComboBox<>();
        imagePanel = new javax.swing.JPanel();
        glassfishLB = new javax.swing.JLabel();
        javaeeLB = new javax.swing.JLabel();
        postgresqlLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menampilkan Gambar dengan Combo Box");

        comboLB.setText("Pilih Gambar");
        comboPanel.add(comboLB);

        pilihCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Glassfish", "JavaEE", "PostgreSQL" }));
        pilihCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pilihCBItemStateChanged(evt);
            }
        });
        comboPanel.add(pilihCB);

        getContentPane().add(comboPanel, java.awt.BorderLayout.PAGE_START);

        imagePanel.setLayout(new java.awt.CardLayout());

        glassfishLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        glassfishLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/glassfish.jpg"))); // NOI18N
        glassfishLB.setToolTipText("null");
        imagePanel.add(glassfishLB, "Glassfish");

        javaeeLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        javaeeLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/javaee.jpg"))); // NOI18N
        javaeeLB.setToolTipText("null");
        imagePanel.add(javaeeLB, "JavaEE");

        postgresqlLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        postgresqlLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/postgresql.png"))); // NOI18N
        postgresqlLB.setToolTipText("null");
        imagePanel.add(postgresqlLB, "PostgreSQL");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pilihCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pilihCBItemStateChanged
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, String.valueOf(pilihCB.getSelectedItem()));
    }//GEN-LAST:event_pilihCBItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilGambarComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel comboLB;
    private javax.swing.JPanel comboPanel;
    private javax.swing.JLabel glassfishLB;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel javaeeLB;
    private javax.swing.JComboBox<String> pilihCB;
    private javax.swing.JLabel postgresqlLB;
    // End of variables declaration//GEN-END:variables
}
